# Site settings
title: πRates
tag_text: Solo
description: Solo is a Jekyll theme that supports single-page websites only, but supports them well. Yes, it’s responsive.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
